# Generated by Django 3.1.5 on 2021-07-14 14:30

from django.db import migrations, models
import test_img.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_img', '0002_imag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imag',
            name='Image',
            field=models.ImageField(upload_to=test_img.models.get_test_img),
        ),
    ]
